/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrasi akun baru (6 field) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifikasi email dengan token sekali pakai (expired 24 jam) */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kirim ulang email verifikasi */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login dengan email terverifikasi */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tukar refresh token menjadi pasangan token baru (rotation) */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (revoke refresh token) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login/daftar via Google ID Token (rate 10/mnt/IP) */
        post: operations["googleLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar user (Org Admin, Super Admin). Untuk memilih Signer. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profil user yang sedang login */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/complete-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Lengkapi profil (onboarding Google); sekali saja */
        patch: operations["completeProfile"];
        trace?: never;
    };
    "/keys/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate key pair (private key dienkripsi AES-256-GCM) */
        post: operations["generateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar key pair milik signer */
        get: operations["listKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke key (Super Admin). Key rotation = revoke + generate baru */
        post: operations["revokeKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar dokumen (paginated, filter status) */
        get: operations["listDocuments"];
        put?: never;
        /** Upload PDF (Org Admin, max 25 MB) */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail dokumen (butuh auth) */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unduh PDF asli / bertanda tangan (privat, butuh auth) */
        get: operations["downloadDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{id}/request-sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Org Admin meminta tanda tangan ke Signer */
        post: operations["requestSign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-requests/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daftar request menunggu tanda tangan (Signer) */
        get: operations["listPendingSignRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-requests/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signer menyetujui + menandatangani satu dokumen (QR tertempel) */
        post: operations["approveSignRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-requests/batch-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch signing (transaksi + optimistic locking) */
        post: operations["batchApproveSignRequests"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signer menolak dokumen beserta alasan */
        post: operations["rejectSignRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify/{sig_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verifikasi publik via QR/link tanpa login */
        get: operations["verifyBySigId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/verify/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verifikasi publik via upload PDF tanpa login */
        post: operations["verifyUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log (Super Admin, Org Admin). Immutable: tanpa POST/PUT/DELETE */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notifikasi in-app user yang login */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            error: {
                /** @example UNAUTHORIZED */
                code: string;
                /** @example Token tidak valid atau kedaluwarsa. */
                message: string;
            };
        };
        MessageResponse: {
            message: string;
        };
        /** @enum {string} */
        Role: "SUPER_ADMIN" | "ORG_ADMIN" | "SIGNER" | "VERIFIER";
        /** @enum {string} */
        KeyAlgorithm: "RSA_PSS_2048" | "ECDSA_P256" | "ED25519";
        /** @enum {string} */
        DocumentStatus: "DRAFT" | "PENDING" | "SIGNED" | "REJECTED";
        /** @enum {string} */
        SignRequestStatus: "PENDING" | "APPROVED" | "REJECTED";
        RegisterRequest: {
            fullName: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            organization: string;
            /** @description Opsional saat register; format internasional, dinormalisasi */
            phone?: string;
            /** @enum {string} */
            role: "ORG_ADMIN" | "SIGNER";
            /** @description Tujuan penggunaan; dicatat di audit log, bukan kolom user */
            purpose: string;
            /** @description Token Turnstile; wajib bila CAPTCHA diaktifkan */
            captchaToken?: string;
        };
        VerifyEmailRequest: {
            /** Format: email */
            email: string;
            token: string;
        };
        ResendVerificationRequest: {
            /** Format: email */
            email: string;
            /** @description Token Turnstile; diverifikasi bila CAPTCHA diaktifkan */
            captchaToken?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            /** @description Opsional; bila diisi akan diverifikasi */
            captchaToken?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        User: {
            id: string;
            fullName: string;
            email: string;
            organization: string;
            role: components["schemas"]["Role"];
            emailVerified: boolean;
            phone?: string | null;
            /** @enum {string} */
            authProvider: "EMAIL" | "GOOGLE";
            profileCompleted: boolean;
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        AuthTokens: {
            accessToken: string;
            refreshToken: string;
            /** @description Detik hingga access token kedaluwarsa (900 = 15 menit) */
            expiresIn: number;
        };
        LoginResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["AuthTokens"];
        };
        GoogleLoginRequest: {
            /** @description Google ID Token dari GIS button */
            idToken: string;
        };
        CompleteProfileRequest: {
            fullName: string;
            organization: string;
            /** @description Wajib saat onboarding; dinormalisasi */
            phone: string;
            /** @enum {string} */
            role: "ORG_ADMIN" | "SIGNER";
            /** @description Dicatat di audit log, bukan kolom user */
            purpose: string;
        };
        GoogleLoginResponse: {
            user: components["schemas"]["User"];
            tokens: components["schemas"]["AuthTokens"];
            /** @description False = FE wajib arahkan ke /onboarding */
            profileCompleted: boolean;
        };
        GenerateKeyRequest: {
            algorithm: components["schemas"]["KeyAlgorithm"];
        };
        KeyPair: {
            id: string;
            algorithm: components["schemas"]["KeyAlgorithm"];
            /** @description PEM / base64 public key */
            publicKey: string;
            revoked: boolean;
            /** Format: date-time */
            revokedAt?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        UploadDocumentRequest: {
            /**
             * Format: binary
             * @description File PDF, max 25 MB
             */
            file: string;
            title: string;
            description?: string;
            /** @description JSON string metadata kanonis yang ikut ditandatangani */
            metadata?: string;
        };
        Document: {
            id: string;
            title: string;
            description?: string | null;
            storagePath: string;
            /** @description SHA-256 hex dari byte PDF asli */
            fileHash: string;
            metadata: Record<string, never>;
            status: components["schemas"]["DocumentStatus"];
            /** @description Optimistic locking untuk batch sign */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        RequestSignRequest: {
            signerId: string;
            message?: string;
        };
        SignRequest: {
            id: string;
            documentId: string;
            signerId: string;
            status: components["schemas"]["SignRequestStatus"];
            message?: string | null;
            rejectReason?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ApproveRequest: {
            keyPairId: string;
        };
        BatchApproveRequest: {
            items: {
                signRequestId: string;
                keyPairId: string;
            }[];
        };
        BatchApproveItemResult: {
            signRequestId: string;
            success: boolean;
            signatureId?: string | null;
            error?: components["schemas"]["ErrorBody"];
        };
        BatchApproveResponse: {
            results: components["schemas"]["BatchApproveItemResult"][];
        };
        RejectRequest: {
            rejectReason: string;
        };
        Signature: {
            /** @description sig_id untuk verifikasi publik */
            id: string;
            documentId: string;
            signerId: string;
            keyPairId: string;
            algorithm: components["schemas"]["KeyAlgorithm"];
            /** @description Base64 signature atas SHA-256(PDF) + metadata kanonis */
            signatureValue: string;
            signedHash: string;
            canonicalMetadata: string;
            /** @description Link verifikasi yang di-embed ke QR */
            qrPayload: string;
            signedPdfPath?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        VerifyResult: {
            /** @enum {string} */
            status: "VALID" | "INVALID";
            documentName?: string;
            signerName?: string;
            /** Format: date-time */
            signedAt?: string;
            reason?: string;
            auditTrail?: {
                event: string;
                /** Format: date-time */
                at: string;
                actor?: string;
            }[];
        };
        AuditLog: {
            id: string;
            actorId?: string | null;
            action: string;
            entity?: string | null;
            entityId?: string | null;
            details: Record<string, never>;
            ipAddress?: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        Notification: {
            id: string;
            type: string;
            title: string;
            message: string;
            isRead: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        DocumentPage: {
            data: components["schemas"]["Document"][];
            page: number;
            limit: number;
            total: number;
        };
        SignRequestPage: {
            data: components["schemas"]["SignRequest"][];
            page: number;
            limit: number;
            total: number;
        };
        AuditLogPage: {
            data: components["schemas"]["AuditLog"][];
            page: number;
            limit: number;
            total: number;
        };
        NotificationPage: {
            data: components["schemas"]["Notification"][];
            page: number;
            limit: number;
            total: number;
        };
        UserPage: {
            data: components["schemas"]["User"][];
            page: number;
            limit: number;
            total: number;
        };
    };
    responses: {
        /** @description Request tidak valid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Token hilang / tidak valid / kedaluwarsa */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Role tidak diizinkan */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Validasi request gagal (tipe/format field salah) */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Melebihi batas request per menit */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Layanan hulu (Google) gagal dijangkau */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Fitur belum dikonfigurasi di server */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Resource tidak ditemukan */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
        /** @description Konflik status (mis. sudah di-sign / double request) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorBody"];
            };
        };
    };
    parameters: {
        IdParam: string;
        PageParam: number;
        LimitParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Terdaftar, email verifikasi terkirim (mode dev: link ada di log server) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email terverifikasi, akun aktif */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description Email terkirim (selalu 200 agar tidak bocor status akun) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login sukses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Email belum terverifikasi */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Token baru */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokens"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logout sukses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleLoginRequest"];
            };
        };
        responses: {
            /** @description Sukses; profileCompleted=false berarti FE wajib ke /onboarding */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleLoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                limit?: components["parameters"]["LimitParam"];
                role?: components["schemas"]["Role"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar user (tanpa hash/token) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteProfileRequest"];
            };
        };
        responses: {
            /** @description Profil lengkap */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    generateKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateKeyRequest"];
            };
        };
        responses: {
            /** @description Key pair terbuat (private key TIDAK pernah dikembalikan plaintext) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["KeyPair"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key di-revoke */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                limit?: components["parameters"]["LimitParam"];
                status?: components["schemas"]["DocumentStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar dokumen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UploadDocumentRequest"];
            };
        };
        responses: {
            /** @description Dokumen terupload, hash SHA-256 dihitung */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail dokumen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    downloadDocument: {
        parameters: {
            query?: {
                kind?: "original" | "signed";
            };
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File PDF (Content-Disposition inline) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    requestSign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestSignRequest"];
            };
        };
        responses: {
            /** @description SignRequest terbuat + notifikasi terkirim ke Signer */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    listPendingSignRequests: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar pending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignRequestPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    approveSignRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveRequest"];
            };
        };
        responses: {
            /** @description Signature terbuat */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Signature"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    batchApproveSignRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchApproveRequest"];
            };
        };
        responses: {
            /** @description Hasil per item (sukses/gagal 개별, tidak setengah jalan) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchApproveResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
        };
    };
    rejectSignRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectRequest"];
            };
        };
        responses: {
            /** @description Ditolak */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignRequest"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    verifyBySigId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sig_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Hasil verifikasi VALID / TIDAK VALID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
        };
    };
    verifyUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Hasil verifikasi VALID / TIDAK VALID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar audit log */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageParam"];
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar notifikasi */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
